remove executable bit from length.in (#40)
it should not have it because it's a
template file and Meson will already
set the executable bit when creating
the output file.

This was causing below error when
building package in Fedora copr:
ERROR: ./usr/share/length/length/length.in has shebang which doesn't start with '/' (@PYTHON@)